draw_self()
var _x = lengthdir_x(36, direction+48)
var _y = lengthdir_y(36, direction+48)
draw_sprite_ext(sprite_index, 2, x+_x, y+_y, image_xscale, image_yscale, compteur_helices, c_white, image_alpha)
var _x = lengthdir_x(36, direction-48)
var _y = lengthdir_y(36, direction-48)
draw_sprite_ext(sprite_index, 2, x+_x, y+_y, image_xscale, image_yscale, compteur_helices, c_white, image_alpha)
var _x = lengthdir_x(36, direction-48+180)
var _y = lengthdir_y(36, direction-48+180)
draw_sprite_ext(sprite_index, 2, x+_x, y+_y, image_xscale, image_yscale, compteur_helices, c_white, image_alpha)
var _x = lengthdir_x(36, direction+48+180)
var _y = lengthdir_y(36, direction+48+180)
draw_sprite_ext(sprite_index, 2, x+_x, y+_y, image_xscale, image_yscale, compteur_helices, c_white, image_alpha)