draw_set_alpha(0.5)
draw_set_color(c_black)
draw_rectangle(0, 0, room_width, room_height, false)
draw_set_alpha(1)
draw_self()
draw_set_color(c_white)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text(x, y, texte)
draw_set_halign(fa_left)
draw_set_valign(fa_top)