draw_set_alpha(0.5)
draw_set_color(c_black)
draw_rectangle(0, 0, room_width, room_height, false)
draw_set_alpha(1)
draw_self()
draw_set_color(c_white)
//draw_set_halign(fa_center)
draw_rectangle(x-1, y-sprite_height/2+30, x+1, y+sprite_height/2-120, false)
draw_set_valign(fa_middle)
draw_text(x-sprite_width/2+50, y, texte[0])
draw_text(x+20, y, texte[1])
//draw_set_halign(fa_left)
draw_set_valign(fa_top)